config/routes.rb
Chianti::Application.routes.draw do

  #get "sessions/new"

  #get "users/new"

  namespace :admin do
    resources :users do
    end
    resources :sessions do
    end
    get "log_out" => "sessions#destroy", :as => "log_out"
    get "log_in" => "sessions#new", :as => "log_in"
    get "sign_up" => "users#new", :as => "sign_up"


    resources :wines do
    end

    resources :wine_categories do
      member do
        get 'remove_banner'
      end
      resources :wines
    end
    resources :wineries do
      member do
        get 'remove_banner'
      end
    end

    resources :pages do
      member do
        get 'remove_banner'
      end
    end
  end

  resources :admin do
    collection do
      get :login
      post :login_submit
    end
  end

  resource :cart do
    resource :checkout do
      member do
        get :details
        get :success
      end
      resources :orders
    end
  end

  resources :wines do
    resource :cart
  end

  match '/wines/category/:title', :controller => "wines/categories", :action => :show
  match '/wines/:category(/:id)', :to => 'wines#show'
  resources :wineries

  resource :contact

  match ':title', :controller => :pages, :action => :show

  root :to => "pages#index"
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  belongs_to :wine
  validates_presence_of :session_id, :wine_id

  def self.find_by_session_id_and_wine session_id, wine
    Cart.includes(:wine).find(:first, :conditions => ["session_id = ? AND wine_id = ?", session_id, wine.id])
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  before_create :add_ordernumber
  validates_presence_of :firstname, :surname, :email, :address, :postalcode, :accountnumber, :accountowner
  validates :email, :presence => true, 
                    :length => {:minimum => 3, :maximum => 254},
                    :uniqueness => true,
                    :format => {:with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i}

  attr_accessor :cart

  def add_ordernumber
    last_ordernumber = 0
    if last_order = Order.last
      last_ordernumber = last_order.ordernumber
    end
    self.ordernumber = last_ordernumber + 1
  end

end

app/models/page.rb
class Page < ActiveRecord::Base
  has_attached_file :banner, :styles => { :banner => "500x100>" }
  validates_presence_of :title, :body
  validates_attachment_content_type :banner, :content_type => ['image/jpeg', 'image/png']

  before_save :save_title_to_url
  
  def save_title_to_url
    self.url = self.title.downcase.gsub(/[^a-z0-9]+/i, '-')
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation

    attr_accessor :password
    before_save :encrypt_password

    validates_confirmation_of :password
    validates_presence_of :password, :on => :create
    validates_presence_of :email
    validates_uniqueness_of :email

    def self.authenticate(email, password)
      user = find_by_email(email)
      if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
        user
      else
        nil
      end
    end

    def encrypt_password
      if password.present?
        self.password_salt = BCrypt::Engine.generate_salt
        self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
      end
    end
end

app/models/wine.rb
class Wine < ActiveRecord::Base
  has_attached_file :image, :styles => { :image => "150x50>" }
  validates_attachment_content_type :image, :content_type => ['image/jpeg', 'image/png']
  validates_presence_of :title, :wine_category_id

  belongs_to :wine_category
  belongs_to :winery

  before_save :save_title_to_url

  def save_title_to_url
    self.url = self.title.downcase.gsub(/[^a-z0-9]+/i, '-')
  end

  def to_param
    url
  end
end

app/models/wine_category.rb
class WineCategory < ActiveRecord::Base
  has_attached_file :banner, :styles => { :banner => "550x148>" }
  has_attached_file :portrait, :styles => { :portrait => "169x290>" }, :default_url => "/images/missing.png"
  validates_presence_of :title, :body
  validates_attachment_content_type :banner, :content_type => ['image/jpeg', 'image/png']
  validates_attachment_content_type :portrait, :content_type => ['image/jpeg', 'image/png']

  before_save :save_title_to_url

  def save_title_to_url
    self.url = self.title.downcase.gsub(/[^a-z0-9]+/i, '-')
  end

  has_many :wines
end

app/models/winery.rb
class Winery < ActiveRecord::Base
  has_attached_file :winery_banner, :styles => { :banner => "550x148>" }
  validates_attachment_content_type :winery_banner, :content_type => ['image/jpeg', 'image/png']

  validates_presence_of :title

  has_many :wines

  before_save :save_title_to_url

  def save_title_to_url
    self.url = self.title.downcase.gsub(/[^a-z0-9]+/i, '-')
  end


  def to_param
    url
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_filter :authorize, :only => "index"
  def index
  end

  def login
  end

  def login_submit
    if params[:username] == "admin" && params[:password] == "welkom123"
      flash[:notice] = t(:welcome)
      cookies[:admin] = true
      redirect_to admin_index_path
    else
      flash[:warning] = t(:error)
      redirect_to login_admin_index_path
    end
  end
 end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def show
    @cart_lines = Cart.includes(:wine).find_all_by_session_id(session_id)
  end

  def create
    wine = Wine.find_by_url!(params[:wine_id])
    if cart = Cart.find(:first, :conditions => ["session_id = ? AND wine_id = ?", session_id, wine.id])
      cart.update_attribute(:quantity,cart.quantity + 1)
      flash[:notice] = t(:anotheradd, :scope => :cart ,:wine => wine.title)
    else
      Cart.create!(:wine => wine, :session_id => session_id, :quantity => 1)
      flash[:notice] = t(:add, :scope => :cart ,:wine => wine.title)
    end
    redirect_to cart_path
  end

  def destroy
    wine = Wine.find_by_url!(params[:wine_id])
    if cart_line = Cart.find_by_session_id_and_wine(session_id, wine)
      flash[:notice] = t(:remove, :scope => :cart ,:wine => wine.title) 
      cart_line.delete
    else
      flash[:warning] = t(:error) 
    end
    redirect_to cart_path
  end

  def update
    wine = Wine.find(params[:cart][:wine_id])
    quantity = params[:cart][:quantity]

    cart_line = Cart.find_by_session_id_and_wine(session_id, wine)
    if cart_line.update_attribute(:quantity,quantity)
      flash[:notice] = t(:quantity, :scope => :cart ,:wine => wine.title, :quantity => quantity)
    end

    redirect_to cart_path
  end

  private

  def session_id
    cookies[:session_id] ||= rand(16**36).to_s(36)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @categories = WineCategory.find_all_by_menu(true)
  end

  def show
    @page = Page.first(:conditions => ['url = ?', params[:title].downcase])
    if @page.nil?
      redirect_to :root
    end
  end
end

app/controllers/wines_controller.rb
class WinesController < ApplicationController
  def index
    @categories = WineCategory.all
  end

  def show
    @wine = WineCategory.find_by_url(params[:category]).wines.find_by_url!(params[:id])
    @current_category = @wine.wine_category
  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/checkouts_helper.rb
module CheckoutsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/wineries_helper.rb
module WineriesHelper
end

app/helpers/wines_helper.rb
module WinesHelper
end

app/views/admin/index.html.haml
%h1 Admin

app/views/admin/login.html.haml
%h1 Login

=form_tag('/admin/login_submit', :method => :post) do
  %p
    =label_tag "username"
    =text_field_tag "username"
  %p
    =label_tag "password"
    =password_field_tag "password"
  =submit_tag "login"
  

app/views/admin/pages/edit.html.haml
%h1==Edit the page #{@page.title}

= form_for [:admin,@page], :html => { :multipart => true } do |f|
  %p
    =f.label :title
    =f.text_field :title
  %p
    =f.label :banner
    =f.file_field :banner
  - unless @page.banner_file_name.nil?
    %p
      =link_to t(:current, :scope => :banner), @page.banner.url(:banner) 
      =link_to t(:deletebanner, :scope => :banner), remove_banner_admin_page_path(@page)
  %p
    =f.label :body
    =ckeditor_textarea("page", "body", :width => '100%', :height => '200px')
  =f.submit t(:save)

app/views/admin/pages/index.html.haml
%h1 Pages

%ul
  %li=link_to t(:new, :scope => :page), new_admin_page_path

%table
  %tr
    %th=t(:name)
    %th=t(:options)
    %th=t(:homepage, :scope => [:page])
  - @pages.each do |page|
    %tr
      %td=page.title
      %td
        =link_to t(:edit), edit_admin_page_path(page)
        =link_to t(:delete), admin_page_path(page), :method => "delete"
      %td
        =form_for [:admin, page] do |f|
          -f.check_box :menu, :class => "addmenu"

app/views/admin/pages/new.html.haml
%h1 New page

= form_for [:admin,@page], :html => { :multipart => true } do |f|
  %p
    =f.label :title
    =f.text_field :title
  %p
    =f.label :banner
    =f.file_field :banner
  - unless @page.banner_file_name.nil?
    %p
      =link_to t(:current, :scope => :banner), @page.banner.url(:banner) 
      =link_to t(:deletebanner, :scope => :banner), delete_banner_admin_page_path(@page)
  %p
    =f.label :body
    =ckeditor_textarea("page", "body", :width => '100%', :height => '200px')
  =f.submit t(:save)

app/views/notifier/confirm_order.html.haml
!!!
%html
  %body
    %h1 Thank you for placing the order. 


    %table
      %tr
        %th Title
        %th Price
        %th Quantity
      - @order.cart.each do |cartline|
        %tr
          %td=cartline.wine.title
          %td=cartline.wine.price
          %td=cartline.quantity

app/views/notifier/contact_form.html.haml
!!!
%head
  %body
    =@contact[:body]

app/views/notifier/send_to_chianti.html.haml
!!!
%html
  %body
    %h1== New order from #{@order.firstname} #{@order.surname}: #{@order.ordernumber}
    %table
      %tr
        %td Firstname
        %td=@order.firstname
      %tr
        %td Surname
        %td=@order.surname
      %tr
        %td Address
        %td=@order.address
      %tr
        %td Postalcode
        %td=@order.postalcode
      %tr
        %td Email
        %td=@order.email
      %tr
        %td Accountnumber
        %td=@order.accountnumber
      %tr
        %td Accountowner
        %td=@order.accountowner
      %tr
        %td Ordernumber
        %td="%06d" % @order.ordernumber

    %table
      %tr
        %th Title
        %th Price
        %th Quantity
      - @order.cart.each do |cartline|
        %tr
          %td=cartline.wine.title
          %td=cartline.wine.price
          %td=cartline.quantity