config/routes.rb
Chianti::Application.routes.draw do

  #get "sessions/new"

  #get "users/new"

  namespace :admin do
    resources :users do
    end
    resources :sessions do
    end
    get "log_out" => "sessions#destroy", :as => "log_out"
    get "log_in" => "sessions#new", :as => "log_in"
    get "sign_up" => "users#new", :as => "sign_up"


    resources :wines do
    end

    resources :wine_categories do
      member do
        get 'remove_banner'
      end
      resources :wines
    end
    resources :wineries do
      member do
        get 'remove_banner'
      end
    end

    resources :pages do
      member do
        get 'remove_banner'
      end
    end
  end

  resources :admin do
    collection do
      get :login
      post :login_submit
    end
  end

  resource :cart do
    resource :checkout do
      member do
        get :details
        get :success
      end
      resources :orders
    end
  end

  resources :wines do
    resource :cart
  end

  match '/wines/category/:title', :controller => "wines/categories", :action => :show
  match '/wines/:category(/:id)', :to => 'wines#show'
  resources :wineries

  resource :contact

  match ':title', :controller => :pages, :action => :show

  root :to => "pages#index"
end

app/models/wine_category.rb
class WineCategory < ActiveRecord::Base
  has_attached_file :banner, :styles => { :banner => "550x148>" }
  has_attached_file :portrait, :styles => { :portrait => "169x290>" }, :default_url => "/images/missing.png"
  validates_presence_of :title, :body
  validates_attachment_content_type :banner, :content_type => ['image/jpeg', 'image/png']
  validates_attachment_content_type :portrait, :content_type => ['image/jpeg', 'image/png']

  before_save :save_title_to_url

  def save_title_to_url
    self.url = self.title.downcase.gsub(/[^a-z0-9]+/i, '-')
  end

  has_many :wines
end

app/controllers/admin/wine_categories_controller.rb
class Admin::WineCategoriesController < ApplicationController
  before_filter :authorize
  layout 'admin'

  def index
    @categories = WineCategory.all
  end

  def new
    @category = WineCategory.new
  end

  def create
    category = WineCategory.new(params[:wine_category])
    if category.save
      flash[:notice] = t(:create, :scope => [:wine,:category])
      redirect_to admin_wine_categories_path
    else
      flash[:warning] = t(:error)
      redirect_to new_admin_wine_category_path
    end
  end

  def update
    category = WineCategory.find(params[:id])
    if category.update_attributes(params[:wine_category])
      flash[:notice] = t(:update, :scope => [:wine,:category])
      redirect_to admin_wine_categories_path
    else
      flash[:warning] = t(:error)
      redirect_to edit_admin_wine_category_path(category)
    end
  end

  def edit
    @category = WineCategory.find(params[:id])
  end

  def destroy
    WineCategory.find(params[:id]).delete
    flash[:notice] = t(:delete, :scope => [:wine, :category])
    redirect_to admin_wine_categories_path
  end

  def remove_banner
    category = WineCategory.find(params[:id])
    category.update_attribute(:banner,nil)
    flash[:notice] = t(:deletebanner, :scope => [:wine, :category])
    redirect_to edit_admin_wine_category_path(category)
  end
end

app/helpers/admin/wine_categories_helper.rb
module Admin::WineCategoriesHelper
end

app/views/admin/wine_categories/edit.html.haml
%h1=t(:edit, :scope => [:wine,:category,:title], :title => @category.title)

= form_for [:admin,@category], :html => { :multipart => true } do |f|
  =f.hidden :id
  %p
    =f.label :title
    =f.text_field :title
  %p
    =f.label :banner
    =f.file_field :banner
  - unless @category.banner_file_name.nil?
    %p
      =link_to t(:current, :scope => :banner), @category.banner.url(:banner) 
      =link_to t(:deletebanner, :scope => :banner), remove_banner_admin_wine_category_path(@category)
  %p
    =f.label :portrait
    =f.file_field :portrait
  - unless @category.portrait_file_name.nil?
    %p
      =link_to t(:current, :scope => :banner), @category.portrait.url(:portrait) 
  %p
    =f.label :body
    =f.cktext_area :body, :toolbar=>'Full', :width=>'100%', :heigth=>'200px'
  =f.submit t(:save)

app/views/admin/wine_categories/index.html.haml
%h1=t(:index, :scope => [:wine,:category,:title])
%ul
  %li=link_to t(:new, :scope => [:wine,:category,:title]), new_admin_wine_category_path
  %li=link_to t(:new, :scope => [:wine]), new_admin_wine_path
  %li=link_to t(:list, :scope => [:wine,:winery]), admin_wineries_path

%table
  %tr{:style => "border-bottom: 1px solid #666;"}
    %th=t(:category, :scope => [:wine, :form])
    %th=t(:title, :scope => [:wine, :form])
    %th=t(:options, :scope => [:wine, :form])
    %th=t(:homepage, :scope => [:wine, :category])
  - @categories.each do |category|
    %tr
      %td{:style => "width: 180px;"}
        %strong=category.title
      %td
      %td
        =link_to t(:edit), edit_admin_wine_category_path(category)
        =link_to t(:delete), admin_wine_category_path(category), :method => "delete"
      %td
        =form_for [:admin, category] do |f|
          -f.check_box :menu, :class => "addmenu"
    - if category.wines.count > 0 
      - category.wines.each do |wine|
        %tr
          %td=""
          %td=wine.title
          %td
            =link_to t(:edit), edit_admin_wine_path(wine.id)
            =link_to t(:delete), admin_wine_path(wine.id), :method => "delete"

app/views/admin/wine_categories/new.html.haml
%h1=t(:new, :scope => [:wine,:category,:title])

= form_for [:admin,@category], :html => { :multipart => true } do |f|
  %p
    =f.label :title
    =f.text_field :title
  %p
    =f.label :banner
    =f.file_field :banner
  %p
    =f.label :portrait
    =f.file_field :portrait
  %p
    =f.label :body
    =ckeditor_textarea("wine_category", "body", :width => '100%', :height => '200px')
  =f.submit t(:save)