config/routes.rb
Chianti::Application.routes.draw do

  #get "sessions/new"

  #get "users/new"

  namespace :admin do
    resources :users do
    end
    resources :sessions do
    end
    get "log_out" => "sessions#destroy", :as => "log_out"
    get "log_in" => "sessions#new", :as => "log_in"
    get "sign_up" => "users#new", :as => "sign_up"


    resources :wines do
    end

    resources :wine_categories do
      member do
        get 'remove_banner'
      end
      resources :wines
    end
    resources :wineries do
      member do
        get 'remove_banner'
      end
    end

    resources :pages do
      member do
        get 'remove_banner'
      end
    end
  end

  resources :admin do
    collection do
      get :login
      post :login_submit
    end
  end

  resource :cart do
    resource :checkout do
      member do
        get :details
        get :success
      end
      resources :orders
    end
  end

  resources :wines do
    resource :cart
  end

  match '/wines/category/:title', :controller => "wines/categories", :action => :show
  match '/wines/:category(/:id)', :to => 'wines#show'
  resources :wineries

  resource :contact

  match ':title', :controller => :pages, :action => :show

  root :to => "pages#index"
end

app/models/winery.rb
class Winery < ActiveRecord::Base
  has_attached_file :winery_banner, :styles => { :banner => "550x148>" }
  validates_attachment_content_type :winery_banner, :content_type => ['image/jpeg', 'image/png']

  validates_presence_of :title

  has_many :wines

  before_save :save_title_to_url

  def save_title_to_url
    self.url = self.title.downcase.gsub(/[^a-z0-9]+/i, '-')
  end


  def to_param
    url
  end
end

app/controllers/admin/wineries_controller.rb
class Admin::WineriesController < ApplicationController
  before_filter :authorize
  layout 'admin'

  def index
    @wineries = Winery.all
  end

  def new
    @winery = Winery.new
  end

  def create
    winery = Winery.new(params[:winery])
    if winery.save
      flash[:notice] = t(:create, :scope => [:wine,:winery])
      redirect_to admin_wineries_path
    else
      flash[:warning] = t(:error)
      redirect_to new_admin_wineries_path
    end
  end

  def edit
    @winery = Winery.find_by_url(params[:id])
  end

  def update
    winery = Winery.find_by_url(params[:id])
    if winery.update_attributes(params[:winery])
      flash[:notice] = t(:update, :scope => [:wine,:winery])
      redirect_to admin_wineries_path
    else
      flash[:warning] = t(:error)
      redirect_to edit_admin_winery_path(winery)
    end
  end

  def destroy
    Winery.find_by_url(params[:id]).delete
    flash[:notice] = t(:delete, :scope => [:wine, :winery])
    redirect_to admin_wineries_path
  end

  def remove_banner
    winery = Winery.find_by_url(params[:id])
    winery.update_attribute(:winery_banner,nil)
    flash[:notice] = t(:deletebanner, :scope => [:wine, :winery])
    redirect_to edit_admin_winery_path(winery)
  end
end

app/controllers/wineries_controller.rb
class WineriesController < ApplicationController
  def index
    if !Winery
      redirect_to winery_path(Winery.first)
    end
  end

  def show
    @winery = Winery.find_by_url!(params[:id])
    @wines = @winery.wines
  end
end

app/helpers/admin/wineries_helper.rb
module Admin::WineriesHelper
end

app/helpers/wineries_helper.rb
module WineriesHelper
end

app/views/admin/wineries/edit.html.haml
%h1=t(:edit, :scope => [:wine,:winery,:title], :title => @winery.title)

= form_for [:admin,@winery], :html => { :multipart => true } do |f|
  %p
    =f.label :title
    =f.text_field :title
  %p
    =f.label :winery_banner
    =f.file_field :winery_banner
  - unless @winery.winery_banner_file_name.nil?
    %p
      =link_to t(:current, :scope => :banner), @winery.winery_banner.url(:banner) 
      =link_to t(:deletebanner, :scope => :banner), remove_banner_admin_winery_path(@winery)
  %p
    =f.label :body
    =f.cktext_area :body, :toolbar=>'Full', :width=>'100%', :heigth=>'200px'
  =f.submit t(:save)

app/views/admin/wineries/index.html.haml
%h1=t(:index, :scope => [:wine,:winery,:title])

%ul
  %li=link_to t(:new, :scope => [:wine,:winery]), new_admin_winery_path

%table
  %tr{:style => "border-bottom: 1px solid #666;"}
    %th=t(:winery, :scope => [:wine, :winery])
    %th=t(:title, :scope => [:wine, :form])
    %th=t(:options, :scope => [:wine, :form])
  - @wineries.each do |winery|
    %tr
      %td{:style => "width: 180px;"}
        %strong=winery.title
      %td
      %td
        =link_to t(:edit), edit_admin_winery_path(winery)
        =link_to t(:delete), admin_winery_path(winery), :method => "delete"
    - if winery.wines.count > 0 
      - winery.wines.each do |wine|
        %tr
          %td=""
          %td=wine.title
          %td
            =link_to t(:edit), edit_admin_wine_path(wine)
            =link_to t(:delete), admin_wine_path(wine), :method => "delete"

app/views/admin/wineries/new.html.haml
%h1=t(:new, :scope => [:wine,:winery,:title])

= form_for [:admin,@winery], :html => { :multipart => true } do |f|
  %p
    =f.label :title
    =f.text_field :title
  %p
    =f.label :winery_banner
    =f.file_field :winery_banner
  %p
    =f.label :body
    =ckeditor_textarea("winery", "body", :width => '100%', :height => '200px')
  =f.submit t(:save)