config/routes.rb
Chianti::Application.routes.draw do

  #get "sessions/new"

  #get "users/new"

  namespace :admin do
    resources :users do
    end
    resources :sessions do
    end
    get "log_out" => "sessions#destroy", :as => "log_out"
    get "log_in" => "sessions#new", :as => "log_in"
    get "sign_up" => "users#new", :as => "sign_up"


    resources :wines do
    end

    resources :wine_categories do
      member do
        get 'remove_banner'
      end
      resources :wines
    end
    resources :wineries do
      member do
        get 'remove_banner'
      end
    end

    resources :pages do
      member do
        get 'remove_banner'
      end
    end
  end

  resources :admin do
    collection do
      get :login
      post :login_submit
    end
  end

  resource :cart do
    resource :checkout do
      member do
        get :details
        get :success
      end
      resources :orders
    end
  end

  resources :wines do
    resource :cart
  end

  match '/wines/category/:title', :controller => "wines/categories", :action => :show
  match '/wines/:category(/:id)', :to => 'wines#show'
  resources :wineries

  resource :contact

  match ':title', :controller => :pages, :action => :show

  root :to => "pages#index"
end

app/models/wine.rb
class Wine < ActiveRecord::Base
  has_attached_file :image, :styles => { :image => "150x50>" }
  validates_attachment_content_type :image, :content_type => ['image/jpeg', 'image/png']
  validates_presence_of :title, :wine_category_id

  belongs_to :wine_category
  belongs_to :winery

  before_save :save_title_to_url

  def save_title_to_url
    self.url = self.title.downcase.gsub(/[^a-z0-9]+/i, '-')
  end

  def to_param
    url
  end
end

app/controllers/admin/wines_controller.rb
class Admin::WinesController < ApplicationController
  before_filter :authorize
  layout "admin"

  def new
    @categories = WineCategory.all
    @wine = Wine.new
  end

  def create
    category = WineCategory.find(params[:wine_category][:id])
    wine = category.wines.new(params[:wine])
    if wine.save
      flash[:notice] = t(:create, :scope => :wine)
      redirect_to admin_wine_categories_path
    else
      flash[:warning] = t(:error)
      redirect_to new_admin_wine_path
    end
  end

  def edit
    @wine = Wine.find(params[:id])
  end

  def update
    wine = Wine.find(params[:id])
    if wine.update_attributes(params[:wine])
      flash[:notice] = t(:update, :scope => :wine, :title => wine.title)
      redirect_to admin_wine_categories_path
    else
      flash[:warning] = t(:error)
      redirect_to edit_admin_wine_path(wine)
    end
  end

  def destroy
    Wine.find(params[:id]).delete
    flash[:notice] = t(:delete, :scope => :wine)
    redirect_to admin_wine_categories_path
  end


end

app/controllers/wines/categories_controller.rb
class Wines::CategoriesController < ApplicationController
  def show
    @category = WineCategory.first(:conditions => ['url = ?', params[:title].downcase])
    if @category.nil?
      redirect_to :root
    else
      @wines = @category.wines.all
    end
    @current_category = @category
  end
end

app/controllers/wines_controller.rb
class WinesController < ApplicationController
  def index
    @categories = WineCategory.all
  end

  def show
    @wine = WineCategory.find_by_url(params[:category]).wines.find_by_url!(params[:id])
    @current_category = @wine.wine_category
  end

end

app/helpers/admin/wines_helper.rb
module Admin::WinesHelper
end

app/helpers/wines/categories_helper.rb
module Wines::CategoriesHelper
end

app/helpers/wines_helper.rb
module WinesHelper
end

app/views/admin/wines/edit.html.haml
%h1=t(:edit, :scope => [:wine,:title], :title => @wine.title)

=link_to t(:view_in_website, :scope => [:wine]), "/wines/#{@wine.url}"

= form_for [:admin,@wine], :html => { :multipart => true }, :url => admin_wine_path(@wine.id) do |f|
  %p
    =f.label t(:category, :scope => [:wine,:form])
    =collection_select(:wine, :wine_category_id, WineCategory.all, :id, :title)
    =link_to t(:new, :scope => [:wine, :category,:title]), new_admin_wine_category_path
  %p
    =f.label t(:winery, :scope => [:wine,:form])
    =collection_select(:wine, :winery_id, Winery.all, :id, :title, :include_blank => true)
    =link_to t(:new, :scope => [:wine,:winery]), new_admin_winery_path
  %p
    =f.label :title
    =f.text_field :title
  %p
    =f.label :sell
    =f.check_box :sell
  %p
    =f.label "#{:price} €"
    =f.text_field :price
  %p
    =f.label :image
    =f.file_field :image
  %p
    =f.label :body
    =f.cktext_area :body, :toolbar=>'Full', :width=>'100%', :heigth=>'200px'
  =f.submit t(:save)

app/views/admin/wines/new.html.haml
%h1=t(:new,:scope => [:wine,:title])

= form_for [:admin,@wine], :html => { :multipart => true } do |f|
  %p
    =f.label t(:category, :scope => [:wine,:form])
    =collection_select(:wine_category, :id, WineCategory.all, :id, :title)
    =link_to t(:new, :scope => [:wine, :category, :title]), new_admin_wine_category_path
  %p
    =f.label :title
    =f.text_field :title
  %p
    =f.label :sell
    =f.check_box :sell
  %p
    =f.label "#{:price} €"
    =f.text_field :price
  %p
    =f.label :image
    =f.file_field :image
  %p
    =f.label :body
    =f.ckeditor_textarea("body", :width => '100%', :height => '200px')
  =f.submit t(:save)